# Домашнее задание 1 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [ ]:
import pandas as pd
import glob
from google.colab import drive

#### Описание данных

В папке Data находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [ ]:
drive.mount('/content/drive',force_remount=True)

csv_students = glob.glob('/content/drive/MyDrive/Python' + "/Students_info_[0-9].csv")
df1 = pd.concat((pd.read_csv(file) for file in csv_students), ignore_index = True)

csv_marks = glob.glob('/content/drive/MyDrive/Python' + "/Students_marks_[0-9].csv")
df2 = pd.concat((pd.read_csv(file) for file in csv_marks), ignore_index = True)

df  = pd.concat([df1, df2], axis=1, join='inner')
df

Mounted at /content/drive

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,index,math score,reading score,writing score
0,900,male,group D,master's degree,standard,none,group10,200,67,84,86
1,901,female,group C,master's degree,standard,none,group10,201,65,81,77
2,902,female,group A,high school,free/reduced,completed,group10,202,69,77,69
3,903,female,group D,bachelor's degree,free/reduced,completed,group10,203,57,69,68
4,904,female,group D,some high school,free/reduced,none,group10,204,59,41,42
...,...,...,...,...,...,...,...,...,...,...,...
995,195,male,group D,associate's degree,standard,none,group2,895,32,34,38
996,196,male,group C,some high school,free/reduced,completed,group2,896,36,29,27
997,197,male,group E,high school,free/reduced,none,group2,897,63,78,79
998,198,female,group B,some college,free/reduced,none,group2,898,67,54,63
999,199,female,group B,bachelor's degree,free/reduced,none,group2,899,65,78,82

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [ ]:
del df['index']
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,male,group D,master's degree,standard,none,group10,67,84,86
1,female,group C,master's degree,standard,none,group10,65,81,77
2,female,group A,high school,free/reduced,completed,group10,69,77,69
3,female,group D,bachelor's degree,free/reduced,completed,group10,57,69,68
4,female,group D,some high school,free/reduced,none,group10,59,41,42
5,male,group D,some college,standard,none,group10,74,71,78
6,male,group B,high school,standard,none,group10,82,62,62
7,female,group D,some college,standard,completed,group10,81,80,76
8,female,group C,bachelor's degree,free/reduced,none,group10,74,81,76
9,male,group E,bachelor's degree,standard,completed,group10,58,61,66

#### Задание 3. Выведите на экран размеры полученной таблицы

In [ ]:
df.size

9000

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [ ]:
#минимум
print("Минимум")
print(df.min(numeric_only=True))
#максимум
print("Максимум")
print(df.max(numeric_only=True))
#среднее
print("Среднее")
print(df.mean(numeric_only=True))
#стандарное отклонение
print("Стандартное отклонение")
df.std(numeric_only=True)

Минимум
math score        0
reading score    17
writing score    10
dtype: int64
Максимум
math score       100
reading score    100
writing score    100
dtype: int64
Среднее
math score       66.089
reading score    69.169
writing score    68.054
dtype: float64
Стандартное отклонение

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [ ]:
df.isin(["none"]).any()

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course         True
group                          False
math score                     False
reading score                  False
writing score                  False
dtype: bool

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [ ]:
print(df.mean(numeric_only=True))

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [ ]:
math_score_none = df.loc[df['test preparation course'] == 'none', 'math score'].mean()
math_score_default = df.loc[df['test preparation course'] == 'completed', 'math score'].mean()
reading_score_none = df.loc[df['test preparation course'] == 'none', 'reading score'].mean()
reading_score_default = df.loc[df['test preparation course'] == 'completed', 'reading score'].mean()
writing_score_none = df.loc[df['test preparation course'] == 'none', 'writing score'].mean()
writing_score_default = df.loc[df['test preparation course'] == 'completed', 'writing score'].mean()
math_score_none, math_score_default, reading_score_default,reading_score_none, writing_score_default, writing_score_none

(65.84423676012462,
 66.52793296089385,
 69.68715083798882,
 68.88006230529595,
 68.76815642458101,
 67.65576323987538)

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [ ]:
df.loc[:,'lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [ ]:
df.rename(columns={"parental level of education": "education", "test preparation course": "test preparation"})

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,male,group D,master's degree,standard,none,group10,67,84,86
1,female,group C,master's degree,standard,none,group10,65,81,77
2,female,group A,high school,free/reduced,completed,group10,69,77,69
3,female,group D,bachelor's degree,free/reduced,completed,group10,57,69,68
4,female,group D,some high school,free/reduced,none,group10,59,41,42
...,...,...,...,...,...,...,...,...,...
995,male,group D,associate's degree,standard,none,group2,32,34,38
996,male,group C,some high school,free/reduced,completed,group2,36,29,27
997,male,group E,high school,free/reduced,none,group2,63,78,79
998,female,group B,some college,free/reduced,none,group2,67,54,63
999,female,group B,bachelor's degree,free/reduced,none,group2,65,78,82

**Зафиксируем минимальный балл для сдачи экзамена**

In [ ]:
passmark = 50
first = df.loc[df['math score'] >= passmark].count()[0]/df.count()[0]
print('Доля сдавших по математике ' + str(first) )
second = df.loc[df['test preparation course'] == 'completed'].loc[df.loc[df['test preparation course'] == 'completed']['math score'] >= passmark].count()[0]/df.count()[0]
print('Доля сдавших по математике после курса ' + str(second))
course_none = df.loc[df['test preparation course'] == 'none']
math_passed = course_none.loc[course_none['math score'] < passmark]
women = math_passed.loc[math_passed['gender'] == 'female']
third =  women.count()[0]/df.count()[0]
print('Доля женщин не сдавших математику без курса ' + str(third))

Доля сдавших по математике 0.865
Доля сдавших по математике после курса 0.32
Доля женщин не сдавших математику без курса 0.055

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [ ]:

import time

start = time.time() ## точка отсчета времени

answer1 = df.groupby(['race/ethnicity']).mean()['reading score']

end = time.time() - start ## собственно время работы программы

print("Время " + str(end))
print(str(answer1))

start2 = time.time() ## точка отсчета времени

answer2 = df.groupby(['parental level of education']).min()['writing score']

end2 = time.time() - start2 ## собственно время работы программы

print("Время " + str(end2))
print(str(answer2))

Время 0.011525392532348633
race/ethnicity
group A    69.393258
group B    68.331579
group C    68.636364
group D    69.660305
group E    70.457143
Name: reading score, dtype: float64
Время 0.009040117263793945
parental level of education
associate's degree    27
bachelor's degree     38
high school           15
master's degree       37
some college          10
some high school      19
Name: writing score, dtype: int64

<ipython-input-13-26415b7702c8>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  answer1 = df.groupby(['race/ethnicity']).mean()['reading score']

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [ ]:
start3 = time.time() ## точка отсчета времени

for race in df['race/ethnicity'].unique():
     print(race + ":" + str(df.loc[df['race/ethnicity'] == race]['reading score'].mean()))

end3 = time.time() - start3 ## собственно время работы программы

if end3 < end:
   print("С помощью встроенных функций быстрее для первого вопроса!")
else:
    print("Циклом быстрее для первого вопроса")

print("Время " + str(end3))

start4 = time.time() ## точка отсчета времени

for education in df['parental level of education'].unique():
     print(education + ":" + str(df.loc[df['parental level of education'] == education]['writing score'].min()))

end4 = time.time() - start4 ## собственно время работы программы

if end4 < end2:
   print("С помощью встроенных функций быстрее для второго вопроса!")
else:
    print("Циклом быстрее для второго вопроса")

print("Время " + str(end4))

group D:69.66030534351145
group C:68.63636363636364
group A:69.3932584269663
group B:68.33157894736843
group E:70.45714285714286
С помощью встроенных функций быстрее для первого вопроса!
Время 0.00577855110168457
master's degree:37
high school:15
bachelor's degree:38
some high school:19
some college:10
associate's degree:27
С помощью встроенных функций быстрее для второго вопроса!
Время 0.004435539245605469

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [ ]:
pd.pivot_table(data=df, index=['gender','parental level of education'])

<ipython-input-15-c0a07040bfc4>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pd.pivot_table(data=df, index=['gender','parental level of education'])

                                    math score  reading score  writing score
gender parental level of education
female associate's degree            67.086207      69.629310      68.870690
       bachelor's degree             64.142857      69.460317      68.841270
       high school                   64.265957      68.776596      66.808511
       master's degree               71.611111      72.472222      73.444444
       some college                  64.525424      68.983051      67.872881
       some high school              64.725275      69.780220      68.384615
male   associate's degree            66.556604      67.952830      66.594340
       bachelor's degree             64.945455      68.181818      65.781818
       high school                   68.205882      71.274510      70.431373
       master's degree               65.000000      70.043478      68.913043
       some college                  67.370370      68.555556      68.027778
       some high school              65.772727      67.204545      65.670455

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [ ]:
import numpy as np
df['Reading_PassStatus'] = np.where(df['reading score'] > 50, 'P', 'F')
df['Writing_PassStatus'] = np.where(df['writing score'] > 50, 'P', 'F')
df['Math_PassStatus'] = np.where(df['math score'] > 50, 'P', 'F')

df['Reading_PassStatus'].value_counts()
df['Math_PassStatus'].value_counts()
df['Writing_PassStatus'].value_counts()

P    876
F    124
Name: Writing_PassStatus, dtype: int64

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [ ]:
df['OverAll_PassStatus'] = np.where( (df['Math_PassStatus'] == 'P') & ( df['Reading_PassStatus'] == 'P') & ( df['Writing_PassStatus'] == 'P') , 'P', 'F')

df['OverAll_PassStatus'].value_counts()

df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score,Reading_PassStatus,Writing_PassStatus,Math_PassStatus,OverAll_PassStatus
0,male,group D,master's degree,standard,none,group10,67,84,86,P,P,P,P
1,female,group C,master's degree,standard,none,group10,65,81,77,P,P,P,P
2,female,group A,high school,free/reduced,completed,group10,69,77,69,P,P,P,P
3,female,group D,bachelor's degree,free/reduced,completed,group10,57,69,68,P,P,P,P
4,female,group D,some high school,free/reduced,none,group10,59,41,42,F,F,P,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,male,group D,associate's degree,standard,none,group2,32,34,38,F,F,F,F
996,male,group C,some high school,free/reduced,completed,group2,36,29,27,F,F,F,F
997,male,group E,high school,free/reduced,none,group2,63,78,79,P,P,P,P
998,female,group B,some college,free/reduced,none,group2,67,54,63,P,P,P,P
999,female,group B,bachelor's degree,free/reduced,none,group2,65,78,82,P,P,P,P

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [ ]:
def GetGrade(average_mark):
  if (average_mark < 50):
    return 'F'
  if (51 < average_mark < 60):
    return 'E'
  if (61 < average_mark < 70):
    return 'D'
  if (71 < average_mark < 80):
    return 'C'
  if (81 < average_mark < 90):
    return 'B'
  if ( average_mark > 91):
    return 'A'

for i in range(df.shape[0]):
  df.loc[i, 'Grade'] = GetGrade(df.mean(numeric_only=True, axis=1)[i])

df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score,Reading_PassStatus,Writing_PassStatus,Math_PassStatus,OverAll_PassStatus,Grade
0,male,group D,master's degree,standard,none,group10,67,84,86,P,P,P,P,C
1,female,group C,master's degree,standard,none,group10,65,81,77,P,P,P,P,C
2,female,group A,high school,free/reduced,completed,group10,69,77,69,P,P,P,P,C
3,female,group D,bachelor's degree,free/reduced,completed,group10,57,69,68,P,P,P,P,D
4,female,group D,some high school,free/reduced,none,group10,59,41,42,F,F,P,F,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,male,group D,associate's degree,standard,none,group2,32,34,38,F,F,F,F,F
996,male,group C,some high school,free/reduced,completed,group2,36,29,27,F,F,F,F,F
997,male,group E,high school,free/reduced,none,group2,63,78,79,P,P,P,P,C
998,female,group B,some college,free/reduced,none,group2,67,54,63,P,P,P,P,D
999,female,group B,bachelor's degree,free/reduced,none,group2,65,78,82,P,P,P,P,C